version: '3.3'
services:
  #
  # The database server.
  #
  db:
    build: ./db
    image: 'dev.codestijl/scuull-db:0.1.0'
    restart: always
    environment:
      - POSTGRES_USER=spring-md
      - POSTGRES_PASSWORD=spring-md-password
      - POSTGRES_DB=smd
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data/
  #
  # Routes requests to the correct service.
  #
  router:
    build: ./scuull-router
    image: 'dev.codestijl/scuull-router:1.0.0'
    restart: always
    ports:
      - '5555:5555'
  #
  # The API server.
  #
  api:
    build: ./scuull-api
    image: 'dev.codestijl/scuull-api:1.0.0'
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://db:5432/smd
      - DB_USER=spring-md
      - DB_PASSWORD=spring-md-password
      - ACTIVE_PROFILE=docker
  #
  # The server with the user interface.
  #
  ui:
    build: ./scuull-ui
    image: 'dev.codestijl/scuul-ui:0.1.0'
    restart: always
# Data volumes.
volumes:
  my-db:
