#
# Turn off the Spring banner.
#
spring:
  main:
    banner-mode: off

  #
  # Move the port to 5555
  #
server:
  port: 5555

  #
  # Turn off discovery
  #
zuul:
  ignored-services: '*'
  sensitive-headers: Cookie,Set-Cookie
  routes:
    sec:
      path: /auth/**
      url: forward:/auth/
    ui:
      path: /**
      url: http://ui:3000/
    api:
      path: /jobs/**
      url: http://api:8080/jobs/